---
title: "Case Study 2"
author: "Jason Owen Jongsoo"
date: "2023-05-01"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Installing packages
install.packages("tidyverse")
install.packages("janitor")
install.packages("lubridate")
install.packages("skimr")

#Loading packages
library(tidyverse)
library(janitor)
library(lubridate)
library(skimr)
```

```{r}
# assignment of datasets to dataframe
daily_activity <- read.csv("Fitbit Data Files/dailyActivity_merged.csv")
daily_sleep <- read.csv("Fitbit Data Files/sleepDay_merged.csv")
weight_log <- read.csv("Fitbit Data Files/weightLogInfo_merged.csv")
```

```{r}
# str(dataframe_name)
str(daily_activity)
str(daily_sleep)
str(weight_log)

# clean the column names of the datasets
daily_activity <- clean_names(daily_activity)
daily_sleep <- clean_names(daily_sleep)
weight_log <- clean_names(weight_log)

# format daily_sleep$sleep_day as .Date as all of the time values are at 12AM
daily_activity$activity_date <- as.Date(daily_activity$activity_date,'%m/%d/%y')
daily_sleep$sleep_day <- as.Date(daily_sleep$sleep_day, '%m/%d/%y')

# weight_log$date is more complicated as it has PM indicator at the end, so we should use parse_date_time
weight_log$date <- parse_date_time(weight_log$date, '%m/%d/%y %H:%M:%S %p')

# change the weight_log$is_manual_report into a logical format
weight_log$is_manual_report <- as.logical(weight_log$is_manual_report)
```

```{r}
# Further add several columns for further analysis
daily_activity$day_of_week <- wday(daily_activity$activity_date, label = T, abbr = T)
daily_activity$total_active_hours = round((daily_activity$very_active_minutes + daily_activity$fairly_active_minutes + daily_activity$lightly_active_minutes)/60, digits = 2)
daily_activity$sedentary_hours = round((daily_activity$sedentary_minutes)/60, digits = 2)

daily_sleep$hours_in_bed = round((daily_sleep$total_time_in_bed)/60, digits = 2)
daily_sleep$hours_asleep = round((daily_sleep$total_minutes_asleep)/60, digits = 2)
daily_sleep$time_taken_to_sleep = (daily_sleep$total_time_in_bed - daily_sleep$total_minutes_asleep)

weight_log <- weight_log %>% 
  select(-c(fat))

weight_log <- weight_log %>% 
  mutate(bmi2 = case_when(
    bmi > 24.9 ~ 'Overweight',
    bmi < 18.5 ~ 'Underweight',
    TRUE ~ 'Healthy'
  ))
```

```{r}
daily_activity_cleaned <- daily_activity[!(daily_activity$calories<=0),]
daily_activity_cleaned <- daily_activity_cleaned[!(daily_activity_cleaned$total_active_hours<=0.00),]
```

```{r}
# export the clean datasets back to the files
write.csv(daily_activity_cleaned, file ='fitbit_daily_activity.csv')
write.csv(daily_sleep, file = 'fitbit_sleep_log.csv')
write.csv(weight_log, file = 'fitbit_weight_log.csv')
```

```{r}
# plotting the datasets

#options(scipen=) will remove any scientific notations

options(scipen = 999)
ggplot(data = daily_activity_cleaned) +
  aes(x = day_of_week, y = total_steps) +
  geom_col(fill =  'blue') +
  labs(x = 'Day of week', y = 'Total steps', title = 'Totap steps taken in a week')
ggsave('total_steps.png')


ggplot(data = daily_activity_cleaned) +
  aes(x = day_of_week, y = very_active_minutes) +
  geom_col(fill =  'red') +
  labs(x = 'Day of week', y = 'Total very active minutes', title = 'Total activity in a week')
ggsave('total_activity.png')


ggplot(data = daily_activity_cleaned) +
  aes(x = day_of_week, y = calories) +
  geom_col(fill =  'brown') +
  labs(x = 'Day of week', y = 'Calories burned', title = 'Total calories burned in a week')
ggsave('total_calories.png')

ggplot(data = daily_activity_cleaned) +
  aes(x= total_active_hours, y = calories) +
  geom_point(color = 'red') +
  geom_smooth() +
  labs(x = 'Total active hours', y = 'Calories burned', title = 'Calories burned vs active hours')
ggsave('calories_burned_vs_active_hours.png')


ggplot(data = daily_activity_cleaned) +
  aes(x= total_steps, y = calories) +
  geom_point(color = 'orange') +
  geom_smooth() +
  labs(x = 'Total steps', y = 'Calories burned', title = 'Calories burned vs total steps')
ggsave('calories_burned_vs_total_steps.png')


ggplot(data = daily_activity_cleaned) +
  aes(x= sedentary_hours, y = calories) +
  geom_point(color = 'purple') +
  geom_smooth() +
  labs(x = 'Sedentary hours', y = 'Calories burned', title = 'Calories burned vs sedentary hours')
ggsave('sedentary_hours_vs_calories_burned.png')

#Lets merge the tables so we can carry out plotting.
activity_weight <- merge(daily_activity_cleaned, weight_log, by=c('id'))

ggplot(data = activity_weight) +
  aes(x = very_active_minutes, y = weight_kg) +
  geom_violin(fill = 'blue') +
  labs(x = 'Very active minutes', y = 'Weight(kg)', title = 'Relationship between weight and physical activity')
ggsave('weight_physical_activity.png')

ggplot(data = activity_weight) +
  aes(x = total_steps, y = weight_kg) +
  geom_violin(fill = 'purple') +
  labs(x = 'Total steps', y = 'Weight(kg)', title = 'Relationship between weight and physical activity')
ggsave('weight_physical_activity.png')

distinct(weight_log, id, .keep_all = T)
```
